title: "Bogdan's public essays"
description: "Various public essays and ad hoc text snippets"
url: "https://gutza.github.io"
baseurl: "/public"
repository: Gutza/public
permalink: "/:year-:month-:day-:title"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  excerpt_only: true
ignore_files:
  - _README.md